# Generated by Django 5.0.2 on 2024-03-25 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
        ('Payments', '0003_alter_payments_amount'),
        ('Projects', '0002_projects_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='client_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Client.client'),
        ),
        migrations.AddField(
            model_name='payments',
            name='project_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Projects.projects'),
        ),
    ]
