# Generated by Django 5.0.2 on 2024-03-25 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0004_payments_client_id_payments_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='project_id',
            new_name='project',
        ),
    ]
